Server sqlalchemy
WeebWare/Ranobe-Honyaku-API pull request #5
Opened 2016-09-24 05:29 UTC by cloudiirain

Reopening: 

1). Very, very, very minimalistic SQLAlchemy models made (Series and Chapter). The goal isn't to be comprehensive. Rather, it's meant to be a functional starting point so that other parts of the app can be worked on (e.g. API, auth) and toyed with tangible examples.

2). Refactored views.py -- namely, split up the application startup code to app.py. The actual views were moved to views/home.py for cleanliness. In addition, the directories for admin, api, and epub were moved into views as well (since these are technically views). Epub directory should probably be deleted because that should be an entirely separate app of its own.

3). config.py -- added because a lot of tutorials I checked had this. app.config.from_object() seems a lot more succinct to me, but it's a stylistic thing. I don't think we should have both a setup.json and a config.py.

4). README has instructions how to setup SQLAlchemy (dev with sqlite for now)

2016-09-24 08:13 UTC, SunDwarf commented on RanobeHonyaku/db_create.py
> +db.create_all()
what is migrations :S

2016-09-24 08:13 UTC, SunDwarf commented on RanobeHonyaku/models/chapter.py
> +    body = db.Column(db.Text)
why are you using a Text type over a bare String type

2016-09-24 08:14 UTC, SunDwarf commented on RanobeHonyaku/models/series.py
> +    def __init__(self, title):
redundant init

2016-09-24 08:14 UTC, SunDwarf commented on RanobeHonyaku/models/user.py
> +    def __init__(self, username, email):
redundant init

2016-09-24 08:14 UTC, SunDwarf commented on RanobeHonyaku/config.py
> +SQLALCHEMY_DATABASE_URI = 'sqlite:///' + os.path.join(basedir, 'app.db')
lol sqlite on a website

2016-09-24 08:16 UTC, Maverun commented on RanobeHonyaku/config.py
> +SQLALCHEMY_DATABASE_URI = 'sqlite:///' + os.path.join(basedir, 'app.db')
bad move.. bad move...

2016-09-24 13:23 UTC, cloudiirain commented on RanobeHonyaku/models/chapter.py
> +    body = db.Column(db.Text)
Corresponds to TEXT or CLOB as opposed to VARCHAR. Could change it to String so the db will reject input that is too long, but we'll need to write validation on the API anyways. Not familiar with how big chapters can get. I think I've seen really really long chapters before.

You did remind me that the I need to make sure this is unicode compatible though.

2016-09-24 13:27 UTC, cloudiirain commented on RanobeHonyaku/config.py
> +SQLALCHEMY_DATABASE_URI = 'sqlite:///' + os.path.join(basedir, 'app.db')
Where does it not say development-only? >_____> Just replace the URI with [mysql or postgre](http://flask-sqlalchemy.pocoo.org/2.1/config/) and it'll work.

2016-09-24 13:28 UTC, cloudiirain commented on RanobeHonyaku/db_create.py
> +db.create_all()
Not yet implemented but will be done eventually.

2016-09-24 13:46 UTC, cloudiirain commented on RanobeHonyaku/config.py
> +SQLALCHEMY_DATABASE_URI = 'sqlite:///' + os.path.join(basedir, 'app.db')
@GetRektByMe needs to decide on a database anyways

2016-09-24 15:04 UTC, SunDwarf commented on RanobeHonyaku/config.py
> +SQLALCHEMY_DATABASE_URI = 'sqlite:///' + os.path.join(basedir, 'app.db')
"it'll work"

Using a different database for development compared to production is terrible. It's a different environment; you will just fall into the trap of developing around SQLite3's flaws.

2016-09-24 15:06 UTC, SunDwarf commented on RanobeHonyaku/models/chapter.py
> +    body = db.Column(db.Text)
in a sane database varchar() can have a very large length too and isn't DBAPI specific

2016-09-24 15:07 UTC, cloudiirain commented on RanobeHonyaku/config.py
> +SQLALCHEMY_DATABASE_URI = 'sqlite:///' + os.path.join(basedir, 'app.db')
I mean, frankly we should be all working on vagrant but we're not. Also, I'm not going to setup a db we're not using in the end -- @GetRektByMe needs to pick one -- sqlite is just temporary

2016-09-24 18:25 UTC, SunDwarf commented
Jesus fucking christ that's a terrible reasoning to switch away from Flask-SQLAlchemy.

If you have a circular import in that case, fix your design, don't switch away from a library.

2016-09-25 00:15 UTC, cloudiirain commented on RanobeHonyaku/db_create.py
> +db.create_all()
Migrations implemented.

2016-09-25 00:15 UTC, cloudiirain commented on RanobeHonyaku/models/chapter.py
> +    body = db.Column(db.Text)
Changed to db.String

2016-09-25 00:15 UTC, cloudiirain commented on RanobeHonyaku/models/series.py
> +    def __init__(self, title):
Removed.

2016-09-25 00:15 UTC, cloudiirain commented on RanobeHonyaku/models/user.py
> +    def __init__(self, username, email):
Removed.

2016-09-25 00:16 UTC, cloudiirain commented on RanobeHonyaku/config.py
> +SQLALCHEMY_DATABASE_URI = 'sqlite:///' + os.path.join(basedir, 'app.db')
Running on postgresql now

2016-09-25 00:27 UTC, ccubed commented on RanobeHonyaku/api/v1/__init__.py
> +from RanobeHonyaku.api.v1.resources.series import SeriesDetail, SeriesList
Relative imports. Have you heard of them?
```python
from .resources.series import SeriesDetail, SeriesList
```

2016-09-25 00:31 UTC, ccubed commented on RanobeHonyaku/api/v1/__init__.py
> +from RanobeHonyaku.utils import setup_file
Why aren't we using relative imports?

2016-09-25 00:33 UTC, ccubed commented on RanobeHonyaku/api/v1/__init__.py
> +@api_v1.route(rule="")
First, don't use rule. Second, the route should be "/".

2016-09-25 00:36 UTC, ccubed commented on RanobeHonyaku/database.py
> +from RanobeHonyaku.models.chapter import *
No stop.

2016-09-25 00:37 UTC, ccubed commented on RanobeHonyaku/models/__init__.py
> +
Why are you importing these in two places. Pick one! This is why you have circular imports!

2016-09-25 00:37 UTC, ccubed commented on RanobeHonyaku/models/chapter.py
> +from RanobeHonyaku.database import db
Whut!? Circular imports incoming!

2016-09-25 00:38 UTC, ccubed commented on RanobeHonyaku/models/series.py
> +from RanobeHonyaku.database import db
Wew lad. Do you understand how this works? Recchan, where did you find this person?

2016-09-25 00:39 UTC, ccubed requested changes
Rebase all this. 13 commits? No. Just no.

2016-09-25 00:58 UTC, cloudiirain commented on RanobeHonyaku/api/v1/__init__.py
> +from RanobeHonyaku.api.v1.resources.series import SeriesDetail, SeriesList
Yep! However [flask docs recommend absolute imports](http://flask.pocoo.org/docs/0.11/patterns/packages/). At least, with the way they suggest that we write runserver.py

2016-09-25 01:02 UTC, cloudiirain commented on RanobeHonyaku/models/chapter.py
> +from RanobeHonyaku.database import db
db needs to be imported to define the model; I don't think this is avoidable. Using the same kind of import that @SunDwarf is [using here.](https://github.com/KanColleTool/kcsrv/blob/master/db/admiral.py)

2016-09-25 01:04 UTC, cloudiirain commented on RanobeHonyaku/database.py
> +from RanobeHonyaku.models.chapter import *
Will remove. This one shouldn't be here/isn't needed.

2016-09-25 03:30 UTC, zeyla commented
What's the point in rebasing while a PR is still under development? You rebase it once it's been approved prior to accepting...

2016-09-25 03:39 UTC, cloudiirain commented on RanobeHonyaku/models/__init__.py
> +
Kept this one.

2016-09-25 03:40 UTC, cloudiirain commented on RanobeHonyaku/api/v1/__init__.py
> +@api_v1.route(rule="")
Changed.

2016-09-25 04:40 UTC, cloudiirain commented on RanobeHonyaku/api/v1/__init__.py
> +from RanobeHonyaku.utils import setup_file
Switched to relative import.

2016-09-25 06:16 UTC, cloudiirain commented
Commit is rebased. PR description is updated with a better summary.

In addition, I've addressed/fixed the suggestions by @SunDwarf and @ccubed.

2016-09-25 16:35 UTC, zeyla commented on RanobeHonyaku/api/v1/resources/chapter.py
> +}
newline on this and the ones below VVV

2016-09-25 16:41 UTC, zeyla commented on RanobeHonyaku/api/v1/resources/series.py
> +        series.title = request.json['title']
AFNP here

2016-09-25 16:41 UTC, zeyla commented on RanobeHonyaku/api/v1/resources/series.py
> +        title = request.json['title']
and here

2016-09-25 16:49 UTC, zeyla commented on RanobeHonyaku/models/chapter.py
> +        return '<Chapter %r>' % (self.series.title + ": " + self.title)
`str.format()` is more powerful than `str % ()`. You can rewrite this as:

```py
return "<Chapter {}:{}>".format(self.series.title, self.title)
```

2016-09-25 16:51 UTC, zeyla commented on RanobeHonyaku/models/chapter.py
> +        return '<Chapter %r>' % (self.series.title + ": " + self.title)
Also I haven't looked at the cases for when Chapter is used, but I'd almost always use `__str__` over `__repl__`. you only really want to use repr for debug

2016-09-25 16:51 UTC, zeyla commented on RanobeHonyaku/models/series.py
> +        return '<Series %r>' % self.title
Same here as above

2016-09-25 16:55 UTC, zeyla commented on README.md
> +may want to consider dropping your database and recreating it.
All lines should be wrapped at 80 characters in markdown documents

2016-09-25 16:58 UTC, zeyla commented on migrations/versions/977a56225963_.py
> +"""empty message
A message would be nice even if it's the initial migration
Even something like "initial"

2016-09-25 17:04 UTC, zeyla commented on RanobeHonyaku/api/v1/__init__.py
> +                "error": self.status_code}
I'm thinking this is against pep8, so it'd be like

```py
return {
    "message": self.message,
    "error": self.status_code,
}
```

source: <https://www.python.org/dev/peps/pep-0008/#indentation>

I'm interpreting the first "No" section to be similar to this but I'm not really certain if it applies to dicts

2016-09-25 17:04 UTC, ghost reviewed
Alright, so most of my stuff is VERY nitpicky. General stuff is pretty good, some of the remaining things I saw I can take a larger look at at a later time, don't have too much time to be in-depth at the moment

One thing I see is that the quotation used (single vs. double) is mixed. A style should probably be adopted for that, but NBD

LGTM with nits and stuff addressed

2016-09-25 17:04 UTC, ghost commented on .gitignore
> +*.db
Probably don't need to keep this gitignore entry

2016-09-25 17:04 UTC, ghost commented on .gitignore
> +.idea/
If .idea/ is going to be ignored absolutely then the entries below can be removed

2016-09-25 17:04 UTC, ghost commented on README.md
> +# Website #
All of these headers should have the hashes solely at the beginning. It's not wrong, but it's probably not recommended, as you have to change the number of hashes in 2 places if you decide to modify the header level

2016-09-25 17:04 UTC, ghost commented on README.md
> +~~~~
These code block fences should be in the style of

```
code
```

You can then modify this piece to reading:

"After running `psql`:
```sql
DELETE DATABASE ranobe_dev;
CREATE DATABASE ranobe_dev;
```
"
This will give you a bit of syntax highlighting:

``` sql
DROP DATABASE ranobe_dev;
CREATE DATABASE ranobe_dev;
```

2016-09-25 17:04 UTC, ghost commented on README.md
> +=# DELETE DATABASE ranobe_dev;
This should be `DROP`, `DELETE` isn't valid in postgres

2016-09-25 17:04 UTC, ghost commented on README.md
> +~~~~
While we're at it, can change these code blocks and headers too

2016-09-25 17:04 UTC, ghost commented on README.md
> +~~~~
Perhaps an empty newline after this codeblock before the text "At this point"? Very nitpicky

2016-09-25 17:04 UTC, ghost commented on RanobeHonyaku/__init__.py
> +import RanobeHonyaku.views
Although it doesn't matter in Python like it does for certain other languages, it's recommended to put a line delimiter (i.e. newline) at the end of files

2016-09-25 17:04 UTC, ghost commented on RanobeHonyaku/__init__.py
> +# Technically a circular import, but this design pattern is recommended by flask docs (and works)
Documentation lines (comments or docstrings) should be limited to 72 characters

2016-09-25 17:04 UTC, ghost commented on RanobeHonyaku/api/README.md
> +### /api/v1/series ###
Nits in this file too

2016-09-25 17:04 UTC, ghost commented on RanobeHonyaku/api/README.md
> +```echo '{"title": "Rawwwwrr2r!"}' | curl -i -d @- http://localhost:5000/api/v1/series --header "Content-Type:application/json"````
This should be three lines and there appears to be an extra grave at the end. You can also use the `shell` language to prettify it:

``` shell
echo '{"title": "Rawwwwrr2r!"}' | curl -i -d @- http://localhost:5000/api/v1/series --header "Content-Type:application/json"
```

via

```shell
echo '{"title": "Rawwwwrr2r!"}' | curl -i -d @- http://localhost:5000/api/v1/series --header "Content-Type:application/json"
```

2016-09-25 17:04 UTC, ghost commented on RanobeHonyaku/api/README.md
> +```curl -X DELETE http://localhost:5000/api/v1/series/6 --header "Content-Type:application/json"```
ditto

2016-09-25 17:04 UTC, ghost commented on RanobeHonyaku/api/README.md
> +```echo '{"title": "Edit this plz!"}' | curl -i -X PUT -d @- http://localhost:5000/api/v1/series/4 --header "Content-Type:application/json"````
ditto

2016-09-25 17:18 UTC, SunDwarf commented on README.md
> +~~~~
Should use a CREATE ROLE and an OWNER directive on that create db call.

2016-09-25 17:19 UTC, Fuyukai commented on RanobeHonyaku/__init__.py
> +# Technically a circular import, but this design pattern is recommended by flask docs (and works)
dont be the pep 8 nazi

2016-09-25 17:19 UTC, SunDwarf commented on RanobeHonyaku/models/chapter.py
> +        return '<Chapter %r>' % (self.series.title + ": " + self.title)
Ideally you'd define `__str__`, and then do `__repr__ = __str__` in the class body.

2016-09-25 17:20 UTC, SunDwarf commented on RanobeHonyaku/api/v1/__init__.py
> +                "error": self.status_code}
That's not against it, but the second one isn't either and looks nicer.

2016-09-25 17:22 UTC, cloudiirain commented on .gitignore
> +.idea/
Removing entries below.

2016-09-25 17:22 UTC, cloudiirain commented on .gitignore
> +*.db
Done

2016-09-25 17:30 UTC, cloudiirain commented on README.md
> +~~~~
```sql
DROP DATABASE ranobe_dev;
CREATE ROLE ranobe_usr WITH LOGIN PASSWORD = '<password>';
CREATE DATABASE ranobe_dev OWNER raobe_usr;
\q
```

2016-09-25 17:33 UTC, cloudiirain commented on README.md
> +~~~~
Done~

2016-09-25 17:33 UTC, cloudiirain commented on README.md
> +~~~~
Done~

2016-09-25 17:33 UTC, cloudiirain commented on README.md
> +may want to consider dropping your database and recreating it.
Done~

2016-09-25 17:34 UTC, cloudiirain commented on RanobeHonyaku/__init__.py
> +# Technically a circular import, but this design pattern is recommended by flask docs (and works)
Done

2016-09-25 17:37 UTC, cloudiirain commented on RanobeHonyaku/__init__.py
> +import RanobeHonyaku.views
Done. Also configured my IDE for this too.

2016-09-25 17:41 UTC, cloudiirain commented on RanobeHonyaku/api/README.md
> +### /api/v1/series ###
Done

2016-09-25 17:41 UTC, cloudiirain commented on RanobeHonyaku/api/README.md
> +```echo '{"title": "Rawwwwrr2r!"}' | curl -i -d @- http://localhost:5000/api/v1/series --header "Content-Type:application/json"````
Done

2016-09-25 17:41 UTC, cloudiirain commented on RanobeHonyaku/api/README.md
> +```echo '{"title": "Edit this plz!"}' | curl -i -X PUT -d @- http://localhost:5000/api/v1/series/4 --header "Content-Type:application/json"````
Done

2016-09-25 17:41 UTC, cloudiirain commented on RanobeHonyaku/api/README.md
> +```curl -X DELETE http://localhost:5000/api/v1/series/6 --header "Content-Type:application/json"```
Done

2016-09-25 17:42 UTC, cloudiirain commented on RanobeHonyaku/api/v1/resources/chapter.py
> +}
Done

2016-09-25 17:46 UTC, cloudiirain commented on RanobeHonyaku/api/v1/resources/series.py
> +        series.title = request.json['title']
Done

2016-09-25 17:46 UTC, cloudiirain commented on RanobeHonyaku/api/v1/resources/series.py
> +        title = request.json['title']
Done

2016-09-25 17:50 UTC, cloudiirain commented on RanobeHonyaku/models/chapter.py
> +        return '<Chapter %r>' % (self.series.title + ": " + self.title)
Done but is this what you mean?

```python
    def __repr__(self):
        return self.__str__
```

2016-09-25 17:54 UTC, cloudiirain commented on RanobeHonyaku/models/series.py
> +        return '<Series %r>' % self.title
done

2016-09-25 17:55 UTC, cloudiirain commented on migrations/versions/977a56225963_.py
> +"""empty message
done

2016-09-25 17:58 UTC, cloudiirain commented on RanobeHonyaku/api/v1/__init__.py
> +                "error": self.status_code}
Done

2016-09-25 17:59 UTC, cloudiirain commented on RanobeHonyaku/models/chapter.py
> +        return '<Chapter %r>' % (self.series.title + ": " + self.title)
nvm zey said this:
```python
class Series(db.Model):

    def __str__(self):
        return "<Series {}>".format(self.title)

    __repr__ = __str__
```

2016-09-25 18:05 UTC, cloudiirain commented
Made all changes recommended by @zelya and updated PR.

2016-09-25 18:13 UTC, Fuyukai approved these changes

2016-09-25 18:22 UTC, merged